# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timmu/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(486, 227)
        self.gridLayoutWidget = QtWidgets.QWidget(MainForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(8, 10, 471, 210))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        self.cmbEstimateUnit = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbEstimateUnit.setObjectName("cmbEstimateUnit")
        self.gridLayout.addWidget(self.cmbEstimateUnit, 5, 2, 1, 1)
        self.lblStatusName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblStatusName.setText("")
        self.lblStatusName.setObjectName("lblStatusName")
        self.gridLayout.addWidget(self.lblStatusName, 1, 3, 1, 1)
        self.txtAddTime = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.txtAddTime.setEditable(True)
        self.txtAddTime.setMaxVisibleItems(5)
        self.txtAddTime.setObjectName("txtAddTime")
        self.gridLayout.addWidget(self.txtAddTime, 3, 0, 1, 1)
        self.chbAutoStart = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chbAutoStart.setObjectName("chbAutoStart")
        self.gridLayout.addWidget(self.chbAutoStart, 3, 3, 1, 1)
        self.lblProgress = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblProgress.setObjectName("lblProgress")
        self.gridLayout.addWidget(self.lblProgress, 6, 0, 1, 1)
        self.lblDuration = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblDuration.setObjectName("lblDuration")
        self.gridLayout.addWidget(self.lblDuration, 4, 0, 1, 1)
        self.spbEstimateValue = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spbEstimateValue.setObjectName("spbEstimateValue")
        self.gridLayout.addWidget(self.spbEstimateValue, 5, 1, 1, 1)
        self.lblStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout.addWidget(self.lblStatus, 4, 1, 1, 2)
        self.txtProject = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.txtProject.setEditable(True)
        self.txtProject.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.txtProject.setObjectName("txtProject")
        self.gridLayout.addWidget(self.txtProject, 1, 1, 1, 2)
        self.lblEstimate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblEstimate.setObjectName("lblEstimate")
        self.gridLayout.addWidget(self.lblEstimate, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnStartStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnStartStop.setEnabled(True)
        self.btnStartStop.setDefault(True)
        self.btnStartStop.setObjectName("btnStartStop")
        self.gridLayout_2.addWidget(self.btnStartStop, 0, 0, 1, 1)
        self.btnBreak = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBreak.setEnabled(True)
        self.btnBreak.setObjectName("btnBreak")
        self.gridLayout_2.addWidget(self.btnBreak, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 1, 1, 2)
        self.lblType = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblType.setObjectName("lblType")
        self.gridLayout.addWidget(self.lblType, 0, 0, 1, 1)
        self.cmbType = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbType.setEnabled(True)
        self.cmbType.setObjectName("cmbType")
        self.gridLayout.addWidget(self.cmbType, 0, 1, 1, 2)
        self.pgbProgress = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.pgbProgress.setProperty("value", 0)
        self.pgbProgress.setObjectName("pgbProgress")
        self.gridLayout.addWidget(self.pgbProgress, 6, 1, 1, 2)
        self.lblStatusName2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblStatusName2.setText("")
        self.lblStatusName2.setObjectName("lblStatusName2")
        self.gridLayout.addWidget(self.lblStatusName2, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.lblProjectName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblProjectName.setObjectName("lblProjectName")
        self.gridLayout.addWidget(self.lblProjectName, 1, 0, 1, 1)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Timmu"))
        self.txtAddTime.setToolTip(_translate("MainForm", "time like \"13:00\" or \"20 minutes ago\""))
        self.chbAutoStart.setText(_translate("MainForm", "Auto-Start"))
        self.lblProgress.setText(_translate("MainForm", "Progress"))
        self.lblDuration.setText(_translate("MainForm", "Current Session"))
        self.txtProject.setToolTip(_translate("MainForm", "Project Name"))
        self.lblEstimate.setText(_translate("MainForm", "Estimate"))
        self.btnStartStop.setText(_translate("MainForm", "Start"))
        self.btnBreak.setText(_translate("MainForm", "Break"))
        self.lblType.setText(_translate("MainForm", "Type"))
        self.lblProjectName.setText(_translate("MainForm", "Project Name"))


