# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timmu/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(1029, 437)
        self.gridLayout = QtWidgets.QGridLayout(MainForm)
        self.gridLayout.setObjectName("gridLayout")
        self.cmbEstimateUnit = QtWidgets.QComboBox(MainForm)
        self.cmbEstimateUnit.setObjectName("cmbEstimateUnit")
        self.gridLayout.addWidget(self.cmbEstimateUnit, 5, 2, 1, 1)
        self.lblProjectName = QtWidgets.QLabel(MainForm)
        self.lblProjectName.setObjectName("lblProjectName")
        self.gridLayout.addWidget(self.lblProjectName, 1, 0, 1, 1)
        self.lblLastSessionInfo2 = QtWidgets.QLabel(MainForm)
        self.lblLastSessionInfo2.setText("")
        self.lblLastSessionInfo2.setObjectName("lblLastSessionInfo2")
        self.gridLayout.addWidget(self.lblLastSessionInfo2, 2, 3, 1, 1)
        self.btnStartStop = QtWidgets.QPushButton(MainForm)
        self.btnStartStop.setEnabled(True)
        self.btnStartStop.setDefault(True)
        self.btnStartStop.setObjectName("btnStartStop")
        self.gridLayout.addWidget(self.btnStartStop, 3, 1, 1, 1)
        self.lblCurrentSessionInfo = QtWidgets.QLabel(MainForm)
        self.lblCurrentSessionInfo.setText("")
        self.lblCurrentSessionInfo.setObjectName("lblCurrentSessionInfo")
        self.gridLayout.addWidget(self.lblCurrentSessionInfo, 4, 1, 1, 1)
        self.lblEstimate = QtWidgets.QLabel(MainForm)
        self.lblEstimate.setObjectName("lblEstimate")
        self.gridLayout.addWidget(self.lblEstimate, 5, 0, 1, 1)
        self.txtProject = QtWidgets.QComboBox(MainForm)
        self.txtProject.setEditable(True)
        self.txtProject.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.txtProject.setObjectName("txtProject")
        self.gridLayout.addWidget(self.txtProject, 1, 1, 1, 2)
        self.chbAutoStart = QtWidgets.QCheckBox(MainForm)
        self.chbAutoStart.setObjectName("chbAutoStart")
        self.gridLayout.addWidget(self.chbAutoStart, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(299, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 3, 1, 1)
        self.lblLastSessionInfo = QtWidgets.QLabel(MainForm)
        self.lblLastSessionInfo.setText("")
        self.lblLastSessionInfo.setObjectName("lblLastSessionInfo")
        self.gridLayout.addWidget(self.lblLastSessionInfo, 1, 3, 1, 1)
        self.lblStatusCurrent = QtWidgets.QLabel(MainForm)
        self.lblStatusCurrent.setObjectName("lblStatusCurrent")
        self.gridLayout.addWidget(self.lblStatusCurrent, 4, 0, 1, 1)
        self.lblCurrentSessionInfo2 = QtWidgets.QLabel(MainForm)
        self.lblCurrentSessionInfo2.setText("")
        self.lblCurrentSessionInfo2.setObjectName("lblCurrentSessionInfo2")
        self.gridLayout.addWidget(self.lblCurrentSessionInfo2, 4, 2, 1, 1)
        self.txtAddTime = QtWidgets.QComboBox(MainForm)
        self.txtAddTime.setEditable(True)
        self.txtAddTime.setMaxVisibleItems(5)
        self.txtAddTime.setObjectName("txtAddTime")
        self.gridLayout.addWidget(self.txtAddTime, 3, 0, 1, 1)
        self.lblType = QtWidgets.QLabel(MainForm)
        self.lblType.setObjectName("lblType")
        self.gridLayout.addWidget(self.lblType, 0, 0, 1, 1)
        self.pgbProgress = QtWidgets.QProgressBar(MainForm)
        self.pgbProgress.setProperty("value", 0)
        self.pgbProgress.setObjectName("pgbProgress")
        self.gridLayout.addWidget(self.pgbProgress, 5, 3, 1, 1)
        self.cmbType = QtWidgets.QComboBox(MainForm)
        self.cmbType.setEnabled(True)
        self.cmbType.setObjectName("cmbType")
        self.gridLayout.addWidget(self.cmbType, 0, 1, 1, 2)
        self.chbGenTimeclock = QtWidgets.QCheckBox(MainForm)
        self.chbGenTimeclock.setObjectName("chbGenTimeclock")
        self.gridLayout.addWidget(self.chbGenTimeclock, 6, 2, 1, 1)
        self.tblWorks = QtWidgets.QTableWidget(MainForm)
        self.tblWorks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblWorks.setObjectName("tblWorks")
        self.tblWorks.setColumnCount(0)
        self.tblWorks.setRowCount(0)
        self.gridLayout.addWidget(self.tblWorks, 7, 1, 1, 3)
        self.treeWorks = QtWidgets.QTreeWidget(MainForm)
        self.treeWorks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWorks.setObjectName("treeWorks")
        self.gridLayout.addWidget(self.treeWorks, 7, 0, 1, 1)
        self.spbEstimateValue = QtWidgets.QSpinBox(MainForm)
        self.spbEstimateValue.setObjectName("spbEstimateValue")
        self.gridLayout.addWidget(self.spbEstimateValue, 5, 1, 1, 1)
        self.lblLastSessionText = QtWidgets.QLabel(MainForm)
        self.lblLastSessionText.setObjectName("lblLastSessionText")
        self.gridLayout.addWidget(self.lblLastSessionText, 0, 3, 1, 1)
        self.btnBreak = QtWidgets.QPushButton(MainForm)
        self.btnBreak.setEnabled(True)
        self.btnBreak.setObjectName("btnBreak")
        self.gridLayout.addWidget(self.btnBreak, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(299, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Timmu"))
        self.lblProjectName.setText(_translate("MainForm", "Project Name:"))
        self.btnStartStop.setText(_translate("MainForm", "Start"))
        self.lblEstimate.setText(_translate("MainForm", "Estimate:"))
        self.txtProject.setToolTip(_translate("MainForm", "Project Name"))
        self.chbAutoStart.setToolTip(_translate("MainForm", "Start last Project after you start this program"))
        self.chbAutoStart.setText(_translate("MainForm", "Auto-Start"))
        self.lblStatusCurrent.setText(_translate("MainForm", "Current Session:"))
        self.txtAddTime.setToolTip(_translate("MainForm", "time like \"13:00\" or \"20 minutes ago\""))
        self.lblType.setText(_translate("MainForm", "Type:"))
        self.chbGenTimeclock.setToolTip(_translate("MainForm", "for hledger"))
        self.chbGenTimeclock.setText(_translate("MainForm", "gen. timeclock-File"))
        self.treeWorks.headerItem().setText(0, _translate("MainForm", "Projects"))
        self.lblLastSessionText.setText(_translate("MainForm", "Last Session:"))
        self.btnBreak.setText(_translate("MainForm", "Break"))


